### ISSUE TITLE
Segfault when a project's root directory does not exist

### ISSUE THREAD

**Issue by smortex** [smortex/wtr#105]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b96f19 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7b96f19 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055555555fc5d in process_working_directory (working_directory=0x555555577040 "/home/romain/Projects/wtr/b") at /home/romain/Projects/wtr/libwtr/libwtr.c:13
#2  0x00005555555602dc in each_user_process_working_directory (callback=0x55555555fc1b <process_working_directory>) at /home/romain/Projects/wtr/libwtr/linux.c:22
#3  0x0000555555558782 in wtr_report (database=0x555555570dc0, options=...) at /home/romain/Projects/wtr/wtr/wtr.c:314
#4  0x000055555555aebe in yyparse (database=0x555555570dc0) at /home/romain/Projects/wtr/wtr/cmd_parser.y:167
#5  0x000055555555833b in main (argc=0, argv=0x7fffffffdf80) at /home/romain/Projects/wtr/wtr/wtr.c:197
(gdb) f 1
#1  0x000055555555fc5d in process_working_directory (working_directory=0x555555577040 "/home/romain/Projects/wtr/b") at /home/romain/Projects/wtr/libwtr/libwtr.c:13
13			if (strnstr(working_directory, projects[i].root, strlen(projects[i].root)) == working_directory &&
(gdb) print i
$1 = 3
(gdb) print projects[3]
$2 = {id = 8, name = 0x555555591ed0 "OpenSearch", root = 0x0, active = 0}
```

**Comment by smortex** [comment]
Fixed by #106
